### ISSUE TITLE
put dates in eastern time

### ISSUE THREAD

**Issue by rshorey** [newsdev/nyt-fec#14]
currently import dates are utc

**Comment by AlJohri** [comment]
I'd be happy to tackle this if you'd like.

**Comment by rshorey** [comment]
@anniedaniel, I leave it to you whether we should convert created/updated dates before storing, or just on display. It wouldn't be terrible to store in eastern, since that's where the FEC is located, but I can also see the argument for sticking to UTC under the hood and just updating the filing template (and any other template that uses dates)

**Comment by AlJohri** [comment]
if you want do it on display, here is an approach that's worked for me (modified from https://docs.djangoproject.com/en/2.1/topics/i18n/timezones/#selecting-the-current-time-zone).

the nice benefit here is that the timezones are displayed properly on django admin tables.

1. create a small middlware that runs `timezone.activate` when rendering any page

```python
import pytz
from django.utils import timezone
from django.utils.deprecation import MiddlewareMixin

class TimezoneMiddleware(MiddlewareMixin):
    def process_request(self, request):
        # tzname = request.session.get('django_timezone')
        tzname = 'US/Eastern'
        if tzname:
            timezone.activate(pytz.timezone(tzname))
        else:
            timezone.deactivate()
```

2) set `TIME_ZONE` to `'UTC'` and `USE_TZ` to `True` in `settings.py` and reference the middleware created above at the end

```python
TIME_ZONE = 'UTC'
USE_TZ = True

MIDDLEWARE = [
    ...,
    'app.middlewares.TimezoneMiddleware'
]
```

**Comment by anniedaniel** [comment]
i'll give it a shot, thanks!

**Comment by anniedaniel** [comment]
@AlJohri your solution worked!! Thanks so much this was super helpful 🎉
