### ISSUE TITLE
max-requests 50 ?

### ISSUE THREAD

**Issue by AlJohri** [newsdev/nyt-fec#54]
hi @rshorey, I was curious why you're using the `max-requests = 50` option in uwsgi. I'm trying to run this and our healthcheck is causing uwsgi to restart the process every minute or two. I'm planning on bumping the value up considerably or removing the option altogether. wanted to check in and see what you thought here

thanks!

**Comment by rshorey** [comment]
I probably just copied from another project and did not think about it, there is definitely no good reason here.
